version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kidfit_postgres
    restart: always
    environment:
      POSTGRES_USER: kidfit_user
      POSTGRES_PASSWORD: kidfit_password
      POSTGRES_DB: kidfit_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kidfit_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: kidfit_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kidfit.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - db
    networks:
      - kidfit_network

volumes:
  postgres_data:


networks:
  kidfit_network:
    driver: bridge
